services:
  - type: web
    name: hackrx-kairos
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: master
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE  
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: OMP_NUM_THREADS
        value: "2"